### ISSUE TITLE
rails-controller-testing gem on RubyGems is not this one

### ISSUE THREAD

**Issue by connorshea** [rails/rails-controller-testing#13]
The `rails-controller-testing` gem recommended by Rails in the deprecation warnings, [as provided by RubyGems](https://rubygems.org/gems/rails-controller-testing), is linked to a different repository from this one. This means that Rails is recommending a gem it doesn't necessary control, even though this repository is more up-to-date than the fork it lists as its homepage. Does the Rails project have control over this gem, or no? Could be a significant security issue if someone else is in control.

**Comment by rafaelfranca** [comment]
Yes we do control this gem as you can see the owners list at the RubyGems page.
