### ISSUE TITLE
Error with TemplateAssertions setup

### ISSUE THREAD

**Issue by bjallen** [rails/rails-controller-testing#16]
Something in 69068e0b662 causes an error when used in a Rails engine.

I have a reduced example in [this repo](https://github.com/bjallen/rails-controller-testing-engine-error-example/commits/master).

```
$ rake test

Error:
Example::ThingsControllerTest#test_GET_index:
NoMethodError: undefined method `each' for nil:NilClass
```

It's coming from a nil `@_subscribers` in the [`teardown_subscriptions` method](https://github.com/rails/rails-controller-testing/blob/3d81f3d6c8ef5060c9e242378a2b64de2aa4d72f/lib/rails/controller/testing/template_assertions.rb#L54).

I don't understand the change well enough to know what the fix might be.

**Comment by bjallen** [comment]
Looks like the error happens with just a normal empty rails app as well. The setup callbacks are run before the ActiveSupport.on_load(:action_controller) block gets lazy loaded, so the TemplateAssertions setup isn't registered in time which means that @_subscribers is never instantiated.

ruby 2.3.0
rails 5.0 beta2

```
rails new example
cd example
echo "gem 'rails-controller-testing', group: :test" >> Gemfile
bundle
rails g scaffold Thing
rails db:migrate
rake test
```

**Comment by maletor** [comment]
I have this issue as well, but with rails 5.0.1 and rails-controller-testing 1.0.1.
