### ISSUE TITLE
With Haml und Rspec view tests, helpers are not found.

### ISSUE THREAD

**Issue by contradictioned** [rails/rails-controller-testing#29]
I have a rails app with the gems `haml-rails` and `rspec`.
I am trying to upgrade this app to rails 5, and since I have `assigns` and `assert_template` in the tests, I added the `rails-controller-testing` gem.

Now the problem: Suddenly, the tests that

1. _render views_ which
2. _include helper methods_

do not work anymore, as the helper methods are not found.

I have a minimal rails app that reproduces this problem here: https://github.com/contradictioned/railsHamlRspecProblem
Is this a problem with this gem or do I miss something here?

**Comment by rafaelfranca** [comment]
We don't support rspec neither haml. Are you able to reproduce this with minitest and ERB?

**Comment by contradictioned** [comment]
No, and even better: The problem does not occur with minitest and haml.

I think that leaves the problem to the way, rspec runs the specs.
