### ISSUE TITLE
Issue with helper test with the last version (1.0.2)

### ISSUE THREAD

**Issue by fwininger** [rails/rails-controller-testing#34]
Hi guys,

We have a issue with the last release.

We use Ruby 2.4.1 and Rails 5.1.1.

With Rspec helper test, this update does something strange. Then we do tests on ClassAHelper with method "name", tests use another helper ClassBHelper than contains also the methode "name".

May be, they have change on the way to load classes ?

Thanks

**Comment by rafaelfranca** [comment]
There is no change in the way it load classes, but if you have to helpers with the same method and they both are being included in the the controller I strongly recommend to rename one of them because the bahavior is not deterministic.

**Comment by fwininger** [comment]
Thanks for your answer.

In the fact, the two helpers are the same method but there are NOT include simultaneously in a controller.

I try to investigate more on this issue when I have some time.

**Comment by rafaelfranca** [comment]
Is the rails configuration to include all helpers disabled?

**Comment by rafaelfranca** [comment]
This issue has closed because there has been no follow-up response from the original author. We currently don't have enough information in order to take action. Please reach out if you have any additional information that will help us move this issue forward.
