### ISSUE TITLE
When gem is only inside :test group, get error NoMethodError:  assert_template has been extracted to a gem. To continue using it, add `gem 'rails-controller-testing'`

### ISSUE THREAD

**Issue by jasonfb** [rails/rails-controller-testing#37]
error:
**NoMethodError:  assert_template has been extracted to a gem. To continue using it, add `gem 'rails-controller-testing'`**

This occurs when the gem is *inside* of the `:test` group in the gemfile (counter-intuitively) 

```
  1) AbcController should call the route
     Failure/Error: assert_template 'index'
     
     NoMethodError:
       assert_template has been extracted to a gem. To continue using it,
               add `gem 'rails-controller-testing'` to your Gemfile.
     # ./spec/controllers/abc_controller_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.06591 seconds (files took 17.29 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/controllers/abc_controller_spec.rb:4 # AbcController should call the route
```

when the gem is *outside* the `:test` group, my specs pass without this error

```
jason@Jasons-MB-Air-2:rails-controller-testing-gem-group-issue-sample-app $ be rspec
Ignoring nokogiri-1.8.0 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.0
/Users/jason/Work/LEARNING/rails_controller_testing/rails-controller-testing-gem-group-issue-sample-app/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/jason/Work/LEARNING/rails_controller_testing/rails-controller-testing-gem-group-issue-sample-app/config/application.rb to limit the frameworks that will be loaded.
..

Finished in 0.07873 seconds (files took 6.02 seconds to load)
2 examples, 0 failures
```

reproduction app coming shortly

**Comment by jasonfb** [comment]
reproduction app here https://github.com/jasonfb/rails-controller-testing-gem-group-issue-sample-app

commit `9c2f789fcf216c31ef8c5a90a90781bf290e0603` will show the symptom

see notes in Gemfile -- I have left the non-buggy line commented out. if you uncomment this line & comment the line in the :test group you should see the effect.

**Comment by rafaelfranca** [comment]
Are you able to reproduce this without RSpec?

**Comment by jrissler** [comment]
I am able to replicate + get the same error with just mini-test (however moving outside test group didn't resolve for me)

**Comment by GBH** [comment]
I started to see this exact problem with one of my projects. ~~Hilariously enough only on MacOS. Ubuntu and TravisCI work perfectly fine. Another project that's using this gem also works fine even on MacOS.~~ Not helping, but I wanted to share

```
Comfy::Admin::Cms::Revisions::PageControllerTest#test_get_show_failure:
NoMethodError: assigns has been extracted to a gem. To continue using it,
        add `gem 'rails-controller-testing'` to your Gemfile.
    actionpack (5.2.0.rc1) lib/action_dispatch/testing/test_process.rb:29:in `assigns'
    actionpack (5.2.0.rc1) lib/action_dispatch/testing/integration.rb:350:in `block (2 levels) in <module:Runner>'
    test/controllers/comfy/admin/blog/revisions/post_controller_test.rb:43:in `test_get_show_failure'
```

**Comment by jasonfb** [comment]
Yes I am on macOS Sierra 10.12.6

@rafaelfranca -- sorry didn't test it elsewhere

**Comment by GBH** [comment]
Something to check. My bundler installed version `0.0.2` (of all versions that there are) instead of `1.0.2` for some reason. That explains why nothing works. Now I need to start digging and figure out why...

Edit: Nuking entire rbenv ruby and then reinstalling and then forcing version to `1.0.2` fixed it for me.

Edit2: Trying to lock versions for other gems makes bundler freak out and not able to find `rails >= 0`. That the is it doing?

Edit3: If you have dependency that itself has a dependency to prerelease gem (like rails 5.2.0.rc1) Bundler freaks out and does weird things. You need to redefine it yourself, like `gem "rails", "~> 5.2.0.rc1"` and then bundler should install everything correctly.

**Comment by jasonfb** [comment]
testing by bumping this gem (rails-controller-testing) from 1.0.2 -> 1.0.4
```
Fetching rails-controller-testing 1.0.4 (was 1.0.2)
Installing rails-controller-testing 1.0.4 (was 1.0.2)
```


the symptom persists. not resolved. 

please re-open

```
/Users/jason/Work/rails-controller-testing-gem-group-issue-sample-app/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/jason/Work/rails-controller-testing-gem-group-issue-sample-app/config/application.rb to limit the frameworks that will be loaded.
F.

Failures:

  1) AbcController should call the route
     Failure/Error: assert_template 'index'
     
     NoMethodError:
       assert_template has been extracted to a gem. To continue using it,
               add `gem 'rails-controller-testing'` to your Gemfile.
     # ./spec/controllers/abc_controller_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.03505 seconds (files took 4.99 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/controllers/abc_controller_spec.rb:4 # AbcController should call the route
```

**Comment by jasonfb** [comment]
please note that these commits bump up this gem from 1.0.2 -> 1.0.4 and also add other security bumps to the example app:

https://github.com/jasonfb/rails-controller-testing-gem-group-issue-sample-app/commit/a6831cbba220e280570410e1e3317570bad24592


but the symptom persists,

```
F.

Failures:

  1) AbcController should call the route
     Failure/Error: assert_template 'index'
     
     NoMethodError:
       assert_template has been extracted to a gem. To continue using it,
               add `gem 'rails-controller-testing'` to your Gemfile.
     # ./spec/controllers/abc_controller_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.09628 seconds (files took 7.47 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/controllers/abc_controller_spec.rb:4 # AbcController should call the route
```

you can reproduce this yourself fairly easily on any brand new Rails app, just add this gem inside only a test group as described above and the symptom will appear.

**Comment by rafaelfranca** [comment]
I can't reproduce with those steps, if I add the gem only in the test group in a new application using minitest it works.

Are you able to reproduce this with minitest or only RSpec?

**Comment by rafaelfranca** [comment]
I just tried in your application to generate a controller test using minitest and use `assert_template` on it and it works fine. This seems to be a bug on rspec-rails.

**Comment by jasonfb** [comment]
- [ ] TODO: get back to @rafaelfranca about question above

**Comment by rafaelfranca** [comment]
hahaha. This is the best comment

**Comment by GBH** [comment]
@jasonfb I just tried your repo and everything works for me
```
..

Finished in 0.02537 seconds (files took 3.92 seconds to load)
2 examples, 0 failures
```

I have `1.0.4` version in a Rails 5.2 and it works just fine. It's 100% something with your environment.

**Comment by petewalker** [comment]
@jasonfb - Just throwing it out there, but is your `RAILS_ENV` set to something other than `test`? That could prevent the gem from being autoloaded by rails.

I had a similar problem in a rails engine that this gem wasn't being autoloaded - as it wasn't in the `Gemfile`, but in the `gemspec`.
