### ISSUE TITLE
Release v1.0.3 

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails-controller-testing#43]
👋 

Would it be possible to release a v1.0.3, mainly interested to get the commit that removes the upperbound constraint on actionpack and actionview

https://github.com/rails/rails-controller-testing/compare/v1.0.2...master

Thanks

cc/ @rafaelfranca

**Comment by rafaelfranca** [comment]
Done

**Comment by Edouard-chin** [comment]
Thanks ❤️
