### ISSUE TITLE
Removing xhr and xml_http_request was non-passive.

### ISSUE THREAD

**Issue by mjhenkes** [rails/rails-controller-testing#44]
Removing xhr and xml_http_request was non-passive and should have been a major version bump.

Tests that were passing using rails-controller-testing 1.0.2 no longer pass with the 1.0.3 release. I'm all for removing the depreciation warning, but it should have been done with a major version bump to give consumers time to upgrade.

Specifically the tests fail with the error:
```ruby
Failure/Error: http_verbs.push('xhr', 'xml_http_request') if ActionPack.version < Gem::Version.new('5.1')

NameError:
  uninitialized constant Rails::Controller::Testing::Integration::ActionPack
```

PR removing xhr and xml_http_request:
https://github.com/rails/rails-controller-testing/pull/32

**Comment by mjhenkes** [comment]
On second glance my issue may just be an error in rails-contoller-testing, although removing xhr and xml_http_request is still non-passive :)

**Comment by rafaelfranca** [comment]
They were not removed. For all rails versions that support them they are still there. For Rails version that doesn't support them they were removed, but it was not working anyway since that Rails version don't have that methods.

**Comment by rafaelfranca** [comment]
1.0.4 released.

**Comment by mjhenkes** [comment]
@rafaelfranca thank you for the quick response :)

**Comment by rafaelfranca** [comment]
Thank you for reporting, in the end it was a oversight in my side.
