### ISSUE TITLE
Release v1.0.5

### ISSUE THREAD

**Issue by corymcdonald** [rails/rails-controller-testing#60]
👋 Hey there, 

Would we be able to get a release created which contains the latest changes? 

https://github.com/rails/rails-controller-testing/compare/v1.0.4...master

Thanks!

cc @rafaelfranca

**Comment by offbyone** [comment]
Seconding this; my specs are pretty noisy due to ruby 2.7 warnings.

**Comment by rafaelfranca** [comment]
@eileencodes you were saying you wanted to do a release for this? If you don't have cycles I can do.

**Comment by eileencodes** [comment]
I can do it, I thought that we had something we were waiting on. I'll do it tomorrow.

**Comment by corymcdonald** [comment]
Thank you all!

**Comment by eileencodes** [comment]
Release is done https://rubygems.org/gems/rails-controller-testing/versions/1.0.5

**Comment by dmarcoux** [comment]
I noticed that the Git tag for `1.0.5` is missing.

**Comment by eileencodes** [comment]
Oops pushed to my fork not to upstream. It's fixed.
