### ISSUE TITLE
Getting "undefined local variable or method `executor_around_each_request'" after edge rails upgrade

### ISSUE THREAD

**Issue by jasnow** [rails/rails-controller-testing#70]
This commit to "rails": https://github.com/rails/rails/commit/5046d1cce90e56e3dc7f42cb394bbd5e740163c8 appears to have affected the rails-controller-testing gem.
Steps to reproduce:
 1. Clone my repo, https://github.com/jasnow/show-me-the-foodedge .
 2. Run "rake" to see a clean run before change.
 3. Run "bundle" to get a new version of edge rails.
 4. Run "rake" again and see the following errors in this gist:
    * https://gist.github.com/jasnow/c1affdc4a7f6371743d164ac5deaae2a
    
  Thanks.

**Comment by jasnow** [comment]
@ghiculescu, @byroot: Ya'll might be able to help with this.

**Comment by byroot** [comment]
Could you add a backtrace too? I'll have a look tomorrow and that would help a lot.

**Comment by ghiculescu** [comment]
Thanks. I’ll have a look at this tomorrow.

**Comment by ghiculescu** [comment]
> I'll have a look tomorrow and that would help a lot.

Race is on 🚀

**Comment by jasnow** [comment]
> Could you add a backtrace too? I'll have a look tomorrow and that would help a lot.

@byroot: Is not the backtrace inside the above gist? If not, how do I create it. Thanks

**Comment by byroot** [comment]
My bad, I only skimmed the issue as I was to go to bed and missed it.

**Comment by byroot** [comment]
Ok, so you use RSpec which probably explains it: https://github.com/jasnow/show-me-the-foodedge/blob/2cb663714dd0bd0c4ab9edc78aadd3f15c70190b/spec/controllers/locations_controller_spec.rb

Really unsure how to fix this, I'm really unfamiliar with how RSpec does these things.

**Comment by byroot** [comment]
@ghiculescu I suppose we  can make it a global flag instead of a `class_attribute`, I kinda liked it that way but...

**Comment by ghiculescu** [comment]
I don’t know rspec either. Maybe accessing the class method instead of the instance method would work here 🤔

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43757

**Comment by ghiculescu** [comment]
You can test by changing the Gemfile to

```ruby
gem 'rails', git: 'https://github.com/ghiculescu/rails', ref: "39cde506c66b565cf8b4d889dcdb61204aabd6c4"
```

**Comment by jasnow** [comment]
Added
````
gem 'rails', git: 'https://github.com/ghiculescu/rails'
````
and it ran cleanly. Will close this issue when fix makes it into edge rails. THANKS!
