### ISSUE TITLE
Eagerly loading AV::TestCase breaks routing

### ISSUE THREAD

**Issue by matthewd** [rails/rails-controller-testing#8]
After adding `rails-controller-testing` to a Gemfile, bundler will automatically require it.

That causes [these lines](https://github.com/rails/rails-controller-testing/blob/43951d086f1de38be3ff48771bf8c55ff92e7162/lib/rails-controller-testing.rb#L19-L21) to run, which in turn triggers the autoload on `ActionView::TestCase`.

That means we run [this line](https://github.com/rails/rails/blob/c403edf9c150693df2477ddcf23dcd52e9bef9ff/actionview/lib/action_view/test_case.rb#L11) too early, before [this initializer](https://github.com/rails/rails/blob/c403edf9c150693df2477ddcf23dcd52e9bef9ff/actionpack/lib/action_controller/railtie.rb#L49-L52) has executed... which means AV tests miss out on all the route helpers.

**Comment by matthewd** [comment]
@sgrif 69068e0b662a048a190cfad34ff64cc359702e59 doesn't seem to fix this for me... I think because the ActionController on_load can still fire before the initializer is run?

**Comment by sgrif** [comment]
Odd. The issue I was resolving is exactly what you've described, and it fixed it for me.
